services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  app:
    build: ./app
    container_name: app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - mongo
    restart: always

  page:
    build: ./page
    container_name: page
    ports:
      - "3000:3000"
    volumes:
      - ./page:/usr/src/app
    command: npm start -- --host 0.0.0.0
    restart: always

volumes:
  mongo_data:
